# GitHub Action for generating a snake game animation showing contributions

name: Generate Snake Game

on:
  # Schedule to execute every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allows manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Update Contribution Snake Game
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generates the snake animation SVG with specified color
      - name: Generate Snake Animation
        uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      # Deploys the generated SVG to the 'output' branch for GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
