name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * 1"  # Every Monday at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if it's the second week of the month
        id: check_week
        run: |
          WEEK_NUM=$(($(date +%d)/7))
          if [ "$WEEK_NUM" -ne 2 ]; then
            echo "Not the second week of the month. Exiting."
            exit 0
          fi

      - name: Generate GitHub Contributions Snake Animations
        if: steps.check_week.outputs.WEEK_NUM == '2'
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        if: steps.check_week.outputs.WEEK_NUM == '2'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Cap Nhat Contribute vao Monday"
